# Generated by Django 5.1 on 2024-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Domain',
            field=models.CharField(max_length=20),
        ),
    ]
