# Generated by Django 5.1 on 2024-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_employee_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Empid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
