# Generated by Django 5.1 on 2024-09-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
